### ISSUE TITLE
Documentation [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#15]
# Overview

Add some documentation describing how to install/set up the package, provide sample prompts, use cases, etc.

# Completion criteria

- [x] create a readme.md file (or modify the current one)
- [x] add a table of contents
- [x] add installation + setup instructions
- [x] add some sample prompts
- [ ] make some fun demo GIFs (screencasts)
