### ISSUE TITLE
Auto-install chatify in neuromatch notebooks [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#19]
# Overview

Automatically install/use chatify in neuromatch notebooks.

# Completion criteria

- [x] fork neuromatch course-content repo (fork is here: https://github.com/ContextLab/course-content/tree/main/tutorials)
- [x] updated initial "imports" blocks to install/import chatify
- [x] Add instructions somewhere to explain how to fetch an explanation for any code block using chatify by adding the `%%explain` magic command and selecting the desired level of explanation
- [x] Submit a pull request back to the main NeuromatchAcademy fork (possibly to a dev branch?) to incorporate our changes into the main materials

# Resources (optional)

An easy way to set up chatify cleanly would be to use my lab's [davos](https://github.com/ContextLab/davos) package.  We just need to add a cell (above the "library imports" cell) in each notebook with the following content:

```python
%pip install davos
import davos

davos.config.supress_stdout = True
```

Then we can add a single line to each library imports cell:

```python
smuggle chatify
```

And the `davos` library should automatically and silently (without creating messy outputs, handling dependencies, etc.) install and set up chatify.

# Discussion points and unknowns (optional)

I wonder if the process of modifying notebooks could be automated by writing a script to add the relevant content to each notebook.
