### ISSUE TITLE
Define a custom magic command [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#2]
# Define a custom magic command

Define a new iPython magic command that enables easy creation of an "explainer" button in markdown cells.  When some template text is found in a markdown cell (`[AUTOEXPLAIN]`?), the iPython parser should "intercept" the text prior to rendering it, and add in a badge or button labeled with something like "Explain!".  When the student clicks the button, it should start the ChatGPT-driven auto-explainer for the surrounding text.  Text and code from prior cells (higher up in the notebook) should also be considered.

# Completion criteria

- [x] Come up with a cool name-- maybe `%autoexplain`?
- [x] Break down the rest of this list into separate TODO issues
- [x] Add a "project scope" issue that defines the MVP functionality
- [x] Come up with a list of core functions
- [x] Add new TODO items (issues) for each core function and link them to the [MVP project board](https://github.com/orgs/ContextLab/projects/3)
- [x] Also tag new TODO items with the [MVP Milestone](https://github.com/ContextLab/chatify/milestone/1)
- [x] Write a "dummy" template that calls placeholder versions of each core function

# Resources (optional)

- iPython docs for defining custom magic commands: [[link](https://ipython.readthedocs.io/en/stable/config/custommagics.html)]
- Tutorial for creating iPython extensions: [[link](https://ipython-books.github.io/14-creating-an-ipython-extension-with-custom-magic-commands/)]
- More about magic commands: [[link](https://www.tutorialspoint.com/jupyter/ipython_magic_commands.htm)
- The `davos` project may have some useful code we can "borrow": [[link](https://github.com/ContextLab/davos)

# Discussion points and unknowns

- Should the autoexplainer just be for equations?  Or also arbitrary tutorial text?
- Do we want the explainer to be fully automatic (e.g., just a single button that can provide additional context or explanation), have a dropdown menu (e.g., explain it to me like i'm: "10 years old", "a high school student", "a college student", "a PhD student", "an expert"), a slider (e.g. to select the desired explanation length), an interactive text box, etc.?  What's the right UI?
- Can we cache previously generated responses to save GPT credits?

**Comment by HemuManju** [comment]
Just for fun asked ChatGPT for a few names, it gave the following

1. CENMAGIC: ChatGPT-Enhanced Neuromatch Magic
2. NEUCHAT: Neuromatch Explained Using ChatGPT 

P.S. NEUCHAT can be pronounced as 'new chat'

**Comment by HemuManju** [comment]
One of the shortcomings of the current magic command is that we cannot adapt to different prompts. So, I am working on an IPython widget to address this problem. It is still preliminary and needs testing.

**Comment by jeremymanning** [comment]
@HemuManju do you want to add an issue to describe your approach, and/or would you like to talk about it at our meeting tomorrow?

**Comment by HemuManju** [comment]
I was able to put together a IPython widget (shown below). It automatically reads the **prompts** folder and populates the UI

I will discuss more on this at tomorrow's meeting. 

https://user-images.githubusercontent.com/16517399/236019317-64257438-797f-4ef2-8fcb-d990b63fdaa4.mov
