### ISSUE TITLE
Button design [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#7]
# Overview

Design the "explainer" button's appearance

# Completion criteria

- [x] Select a button shape
- [x] Create an SVG graphic (if needed)
- [x] Decide on button color + font-- should look good on light/dark backgrounds, at various sizes, on different sized screens, mobile/desktop browsers, etc.
- [x] Choose button text
- [x] Create a mockup of the button and put an image in the "images" folder (create if needed)

**Comment by jeremymanning** [comment]
link to proposed button: [[link](https://github.com/ContextLab/chatify/blob/main/images/button.svg)]
